[2022-10-11 09:53:05,311][set_app.py 192][INFO]: 地址自动获取成功，用例正常！
