[32mINFO    [0m log:set_app.py:557 退出登录成功，用例无异常！